project:
  type: website
  output-dir: docs

website:
  title: "Мой итоговый проект (Вариант 2) "
  navbar:
    left:
      - href: index.qmd
        text: Размеченный текст
      - about.qmd

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true



